matches:
  # 日時
  - trigger: ";now"
    replace: "{{now}}"
    vars:
      - name: "now"
        type: "date"
        params:
          format: "%Y-%m-%d"
  - trigger: ";genz"
    replace: "現在（{{now}}）"
    vars:
      - name: "now"
        type: "date"
        params:
          format: "%Y-%m-%d"
  - trigger: ";genj"
    replace: "現状（{{now}}）"
    vars:
      - name: "now"
        type: "date"
        params:
          format: "%Y-%m-%d"
  - trigger: ";iso"
    replace: "{{iso}}"
    vars:
      - name: "iso"
        type: "date"
        params:
          format: "%Y-%m-%dT%H:%M:%S"
  - trigger: ";ts"
    replace: "{{ts}}"
    vars:
      - name: "ts"
        type: "date"
        params:
          format: "%Y%m%d%H%M%S"
  - trigger: ";end"
    replace: "23:59"

  # Obsidian
  - trigger: ";ot"
    replace: "➕ {{today}} 🛫 {{today}}"
    vars:
      - name: "today"
        type: "date"
        params:
          format: "%Y-%m-%d"
  - trigger: ";["
    replace: "[[$|$]]"

  # 絵文字
  - trigger: ";gd"
    replace: "👍️"
  - trigger: ";plz"
    replace: "🙏"
  - trigger: ";ok"
    replace: "👌"
  - trigger: ";pw"
    replace: "💪"
  - trigger: ";bow"
    replace: "🙇‍♂️"

  # テキスト
  - trigger: ";lorem"
    replace: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  - trigger: ";thx"
    replace: "ありがとうございます"
  - trigger: ";shou"
    replace: "承知しました"
  - trigger: ";chk"
    replace: "ご確認よろしくお願いします"
  - trigger: ";y"
    replace: "Yes"

  # 記号
  - trigger: ";;"
    replace: "_"
  - trigger: ";-"
    replace: "|"
  - trigger: ";."
    replace: "/"
  - trigger: ";v "
    replace: "- "
  - trigger: ";vc"
    replace: "---"

  # ネットワーク
  - trigger: ";lh"
    replace: "http://localhost:"
  - trigger: ";li"
    replace: "http://127.0.0.1:"

  # クリップボード活用
  - regex: ";cb(?P<lang>\\w*) "
    replace: "```{{lang}}\n{{clipboard}}\n```"
    vars:
      - name: "clipboard"
        type: "clipboard"
  - trigger: ";ci"
    replace: "`{{clipboard}}`"
    vars:
      - name: "clipboard"
        type: "clipboard"

  # コマンド
  - regex: ";z(?P<session>\\w+) "
    replace: "zellij a -c {{session}}"
  - trigger: ";wsw"
    replace: "wt switch "

  # AI
  - trigger: ";ab"
    replace: "壁打ちしてください。"
  - trigger: ";ai"
    replace: "改善案を示してください。"
  - trigger: ";ar"
    replace: "調査してください。"
  - trigger: ";awr"
    replace: "Webで調査してください。"
  - trigger: ";af"
    replace: "修正してください。"
  - trigger: ";at"
    replace: "対応してください。"
  - trigger: ";ane"
    replace: "編集は不要です。"
  - trigger: ";ant"
    replace: "対応は不要です。"
  - trigger: ";asr"
    replace: "セルフレビューしてください。"
  - trigger: ";aad"
    replace: "アドバイスしてください。"
  - trigger: ";aex"
    replace: "簡単に説明してください。"
  - trigger: ";acp"
    replace: "コミットして、プッシュしてください。"
  - trigger: ";aoc"
    replace: "一度だけコミットしてください。"
  - trigger: ";aq"
    replace: "これはただの質問です。"
  - trigger: ";aas"
    replace: "これはただの相談です。"

  # Neovim
  - trigger: ";vy"
    replace: "%y+\n"

  # ファイル名
  - trigger: ";fdc"
    replace: "docker-compose.yaml"
  - trigger: ";fdf"
    replace: "Dockerfile"
  - trigger: ";fgi"
    replace: ".gitignore"
  - trigger: ";frm"
    replace: "README.md"
  - trigger: ";fcl"
    replace: "CHANGELOG.md"
  - trigger: ";fjf"
    replace: "justfile"
  - trigger: ";fmi"
    replace: "mise.toml"
  - trigger: ";fcs"
    replace: "cspell.json"
